name: .NET Build and Publish

on:
  push:
    branches: ["main", "dev", "dui3/alpha", "dui3/ci/*"]
    tags: ["3.*"]

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x

      - name: NuGet Cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: "5.x"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Determine Version
        id: version
        uses: gittools/actions/gitversion/execute@v1.1.1

      - name: üóÑÔ∏è Format
        run: ./build.ps1 format

      - name: ‚ôªÔ∏è Restore
        run: ./build.ps1 restore

      - name: ‚öíÔ∏è Build
        run: ./build.ps1 build
        env:
          VERSION: ${{ env.fullSemVer }}
          FILE_VERSION: ${{ env.assemblySemFileVer }}

      - name: üì¶ Pack
        run: ./build.ps1 zip

      - name: ‚¨ÜÔ∏è Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ env.fullSemVer }}
          path: output/*.*
          compression-level: 0 # no compression

      - name: üî´ Trigger Build Installers
        uses: ALEEF02/workflow-dispatch@v3.0.0
        with:
          workflow: Build Installers
          repo: specklesystems/connector-installers
          token: ${{ secrets.CONNECTORS_GH_TOKEN }}
          inputs: '{ "run_id": "${{ github.run_id }}", "version": "${{ env.fullSemVer }}" }'
          ref: main
          wait-for-completion: true
          wait-for-completion-interval: 10s
          wait-for-completion-timeout: 10m
          display-workflow-run-url: true
          display-workflow-run-url-interval: 10s
          workflow-logs: true
