name: .NET Build and Publish

on:
  push:
    branches: ["main", "dev", "dui3/alpha"] # Continuous delivery on every long-lived branch
    tags: ["3.*"] # Manual delivery on every 3.x tag
  pull_request:
    branches: ["main", "dev"] # Releases on every PR that targets main or dev

jobs:
  build:
    uses: ./.github/workflows/ci.yml

  # deploy-installers:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: ðŸ”« Trigger Build Installers
  #       uses: ALEEF02/workflow-dispatch@v3.0.0
  #       with:
  #         workflow: Build Installers
  #         repo: specklesystems/connector-installers
  #         token: ${{ secrets.CONNECTORS_GH_TOKEN }}
  #         inputs: '{ "run_id": "${{ github.run_id }}", "version": "${{ needs.build.outputs.version }}" }'
  #         ref: main
  #         wait-for-completion: true
  #         wait-for-completion-interval: 10s
  #         wait-for-completion-timeout: 10m
  #         display-workflow-run-url: true
  #         display-workflow-run-url-interval: 10s
